version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db_laravel
      MYSQL_USER: ilhamydn
      MYSQL_PASSWORD: ilham123
      MYSQL_ROOT_PASSWORD: ilham123
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
